FROM node:alpine

WORKDIR /rack/client

COPY package*.json .

RUN npm install
COPY . .

RUN npm build

COPY . .
EXPOSE 3000

CMD ["npm", "run", "serve"]

FROM nginx:alpine

COPY --from=build /rack/client/dist /usr/share/nginx/html
EXPOSE 80