FROM node:alpine as build-stage

WORKDIR /rack/client

COPY package*.json ./

RUN npm install
COPY . .

RUN npm run build

COPY . .

FROM nginx:alpine

COPY --from=build-stage /rack/client/dist /usr/share/nginx/html
COPY --from=build-stage rack/client/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
